---
title: "CompareMethods"
author: "Charlotte Bunnenberg"
date: "18 7 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PhaseTypeR)
library(tidyverse)
library(grid)
library(gridExtra)
library(reshape2)
#plot graph
library(igraph)
library(ggplot2)
library(gtools)
# ggplot settings
theme_set(
  theme_minimal() +
    theme(legend.position = "right")
  )
cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

# Compare the results of the exact probability of a sample against the probability returned by alberti's approach for a sample: (0,0)(0,1)
with theta = t and rho = r
```{r}
#original function
exact_probability = function(r){(2*t*(1024*t^6*(1/r)^4+256*t^5*(1/r)^3*(1+22*(1/r))+(1+13*(1/r)+18*(1/r)^2)^2+32*t^3*(1/r)^2*(11+146*(1/r)+432*(1/r)^2)+16*t^4*(1/r)^2*(1+112*(1/r)+772*(1/r)^2)+4*t^2*(1/r)*(11+238*(1/r)+1364*(1/r)^2+2088*(1/r)^3)+t*(2+74*(1/r)+804*(1/r)^2+2736*(1/r)^3+2592*(1/r)^4)))/((1+2*t)^2*(1+13*(1/r)+18*(1/r)^2+64*t^3*(1/r)^2+8*t^2*(1/r)*(3+20*(1/r))+2*t*(1+19*(1/r)+54*(1/r)^2))^2)}
alberti_probability = function(r){(2*t/(1+2*t)^3)-(1/r)*((4*t^2)/(1+2*t)^3)}
#for t = 0.1
exact_probability_0.1 = function(r){(2*0.1*(1024*0.1^6*(1/r)^4+256*0.1^5*(1/r)^3*(1+22*(1/r))+(1+13*(1/r)+18*(1/r)^2)^2+32*0.1^3*(1/r)^2*(11+146*(1/r)+432*(1/r)^2)+16*0.1^4*(1/r)^2*(1+112*(1/r)+772*(1/r)^2)+4*0.1^2*(1/r)*(11+238*(1/r)+1364*(1/r)^2+2088*(1/r)^3)+0.1*(2+74*(1/r)+804*(1/r)^2+2736*(1/r)^3+2592*(1/r)^4)))/((1+2*0.1)^2*(1+13*(1/r)+18*(1/r)^2+64*0.1^3*(1/r)^2+8*0.1^2*(1/r)*(3+20*(1/r))+2*0.1*(1+19*(1/r)+54*(1/r)^2))^2)} 

alberti_probability_0.1 = function(r){(2*0.1/(1+2*0.1)^3)-(1/r)*((4*0.1^2)/(1+2*0.1)^3)}
# for t = 1
exact_probability_1 = function(r){(2*1*(1024*1^6*(1/r)^4+256*1^5*(1/r)^3*(1+22*(1/r))+(1+13*(1/r)+18*(1/r)^2)^2+32*1^3*(1/r)^2*(11+146*(1/r)+432*(1/r)^2)+16*1^4*(1/r)^2*(1+112*(1/r)+772*(1/r)^2)+4*1^2*(1/r)*(11+238*(1/r)+1364*(1/r)^2+2088*(1/r)^3)+1*(2+74*(1/r)+804*(1/r)^2+2736*(1/r)^3+2592*(1/r)^4)))/((1+2*1)^2*(1+13*(1/r)+18*(1/r)^2+64*1^3*(1/r)^2+8*1^2*(1/r)*(3+20*(1/r))+2*1*(1+19*(1/r)+54*(1/r)^2))^2)}
alberti_probability_1 = function(r){(2*1/(1+2*1)^3)-(1/r)*((4*1^2)/(1+2*1)^3)}

df <- data.frame(x=c(0.5, 10))
t<-10
#plot curve in ggplot2
plt <- ggplot(data=df, aes(x=x)) + 
  stat_function(fun=exact_probability_0.1, aes(linetype = "Exact", colour = "0.1"))+
  stat_function(fun=alberti_probability_0.1, aes(linetype = "Loose linkage", colour = "0.1"))+
  stat_function(fun=exact_probability, aes(linetype = "Exact", colour = "10"))+
  stat_function(fun=alberti_probability, aes(linetype = "Loose linkage", colour = "10"))+
  stat_function(fun=exact_probability_1, aes(linetype = "Exact", colour = "1"))+ 
  stat_function(fun=alberti_probability_1, aes(linetype = "Loose linkage",colour = "1"))+
    scale_linetype_manual("Method", values = c("Exact" = "solid", "Loose linkage" = "dashed"))+
    scale_colour_manual(name = expression(theta), values=c("#E69F00",  "#009E73","#56B4E9"))+
  theme(legend.position = "right")+ xlab(expression(rho))+ ylab("Sample probability")
ggsave(file="Compare_Alberti.pdf", plot=plt, width=5, height=3)
```


